### ISSUE TITLE
Allow passing onMouseDown

### ISSUE THREAD

**Issue by jide** [rmarganti/re-position#11]
The mousedown event is swallowed by the container , thus implementing something like a "select element" where I'd need to control mousedown is harder.

**Comment by rmarganti** [comment]
I have implemented the functionality you describe in a production application, so I know this works. I am assuming you are using `<PositionableContainer />`.  A few things to consider.

- Any props non re-position specific are attached to the root element (a `div` by default). So this is the element that will receive your `onMouseDown`.
- The TransformBox (the component with the resize/rotate/etc handles) is rendered on top of the root element (and possibly other html elements due to a z-index value). That means the TransformBox will block your root container's mouse events when it is visible.
- Taking the above into account, the best way to handle "select element" functionality is to hide disable re-position (which hides the TransformBox) when an element isn't selected. Then, attach your selection logic to `onMouseDown`/`onClick`/etc., which will now not be blocked by the TransformBox.

Rough code:

```js
<PositionableContainer
  disabled={!isSelected}
  onMouseDown={isSelected ? undefined : yourSelectFunction}
/>
  {...your children}
</PositionableContainer>
```

Note: `<PositionableContainer />` is meant to be a generic implementation of `<Positionable />` and may not account for all use cases. Once you start implementing more specific/advanced logic, you may need to consider using `<Positionable />`.

**Comment by jide** [comment]
Actually that's how I first implemented it.

But then I wanted to be able to shift click an element to add it to the selection, and a click on a selected element would remove it from selection. That implies that it is not disabled at this moment unfortunately.

Funnily, when not using React's synthetic event but a vanilla event on a child element it's doable, that's how I implemented it in the end, using a ref. Leaving the implem here in case someone is interested.

```js
export function useClickable(ref, toggleSelection) {
  useEffect(() => {
    const node = ref.current;

    const downListener = event => {
      const originalX = event.pageX;
      const originalY = event.pageY;

      let moved = false;

      const moveListener = e => {
        if (
          Math.abs(e.pageX - originalX) > 5 ||
          Math.abs(e.pageY - originalY) > 5
        ) {
          moved = true;
          node.addEventListener('mousemove', moveListener);
        }
      };

      const upListener = e => {
        if (!moved) {
          toggleSelection(!e.metaKey);
        }

        moved = false;
        node.removeEventListener('mousemove', moveListener);
        node.removeEventListener('mouseup', upListener);
      };

      node.addEventListener('mousemove', moveListener);
      node.addEventListener('mouseup', upListener);
    };

    node.addEventListener('mousedown', downListener);

    return () => {
      node.removeEventListener('mousedown', downListener);
    };
  });

  return ref;
}
```

```js
// This is used in the render prop of Positionable
function PositionableRender({
  renderedPosition,
  refHandlers,
  selected,
  toggleSelection
}) {
  const ref = useRef(null);
  useClickable(ref, toggleSelection);

  const style = {
    left: renderedPosition.left,
    width: renderedPosition.width
  };

  return (
    <Fragment>
      <InnerBlock
        innerRef={refHandlers.container}
        style={style}
        selected={selected}
      >
        <Selectable innerRef={ref} selected={selected}>
          <span>Hello!</span>
        </Selectable>
        {selected && (
          <Fragment>
            <LeftHandle innerRef={refHandlers.wResize} />
            <RightHandle innerRef={refHandlers.eResize} />
          </Fragment>
        )}
      </InnerBlock>
    </Fragment>
  );
}
```

**Comment by rmarganti** [comment]
Yeah, this is a place where a custom `<Positionable />` implementation is necessary. In my own use case, I am manually adding an `onClick` to the container component when it is not selected (`disabled` == `true`) and adding the `onClick` to the `<TransformBox />` when it is selected (`disabled` === `false`).

I'm going to leave this issue open for now with one of two eventual outcomes:
- We're able to implement this exactly as you expect with `<PositionableContainer />` or
- (more likely) I can provide an example of implementing this via `<Positionable />`

**Comment by jide** [comment]
I see. I tried this too but when moving the box the onClick event is fired after a move when the mouse is released, that's why I ended up using a combination of mouseDown/Up/Move events and track the mouse position. I'm curious, did you also notice this problem ?

**Comment by jide** [comment]
To be more precise: this is the normal behaviour of a "click" dom event, if the mouse is down, then moved, then released, it's still considered a click event by the browser, but when combined with a dragging behaviour this makes the click event unusable. Or maybe I overlooked something ?

**Comment by rmarganti** [comment]
You're 100% right. In my own use case, we hadn't implemented "shift-click to unselect" yet. But I am able to reproduce this issue exactly as you described. Will have to look into a possible solution.

**Comment by rmarganti** [comment]
There is currently a working branch for this issue. Still needs some additional testing, manual and automated.

https://github.com/rmarganti/re-position/tree/f-click-events

Basically, `<Positionable />` will get the `onClick` prop, so that it can manage the click events and differentiate them from other mouse interactions (like drag and drop).

**Comment by rmarganti** [comment]
This is going live in `0.6.0` now.  `<Positionable />` now accepts an onClick prop. The following considerations are important.

- Your `onClick` callback will receive a DOM `mousedown` event. In order to track whether clicks are actual clicks or drag-and-drop interactions, we have to monitor `mousedown` (and `mouseup`) instead of `click` events. But the concept of a `click` is still important as a concept here, hence `onClick` instead of `onMouseDown`. Note: This is native DOM event, not a React synthetic event. 

- The click observable will prefer to monitor the `dnd` ref over the `container` ref. In practice, this means it will monitor your "Transform Box" when it is displayed and your container when it's not. See `<PositionableContainer />` for reference.
